### ISSUE TITLE
`npm run build`時にtoo many open filesというエラーが発生し、ビルドできない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey#1741]
- 発生箇所はまちまち
- `gulp build`で発生する
- 解決策としてgraceful-fs というパッケージもあるらしいが、gulpで発生しているので書き換えられない
- OS側の制限値を上げるのを求めるのはあまりよくない気がする

```
[00:12:51] Requiring external module ts-node/register
[00:13:17] Using gulpfile ~/misskey/gulpfile.ts
[00:13:17] Starting 'build:ts'...
[00:13:18] Starting 'build:copy:views'...
[00:13:18] Starting 'build:client:script'...
[00:13:18] Starting 'build:client:styles'...
[00:13:18] Starting 'doc:docs'...
[00:13:18] Starting 'doc:api:endpoints'...
[00:13:18] Starting 'doc:api:entities'...
[00:13:18] Starting 'doc:styles'...
[00:13:20] Finished 'build:client:styles' after 2.37 s
[00:13:32] Finished 'build:copy:views' after 14 s
[00:13:32] Starting 'build:copy'...
Error: EMFILE: too many open files, scandir '/home/aqz/misskey/src/acct'
```
```
[00:15:21] Requiring external module ts-node/register
[00:15:25] Using gulpfile ~/misskey/gulpfile.ts
[00:15:25] Starting 'build:ts'...
[00:15:25] Starting 'build:copy:views'...
[00:15:25] Starting 'build:client:script'...
[00:15:25] Starting 'build:client:styles'...
[00:15:25] Starting 'doc:docs'...
[00:15:25] Starting 'doc:api:endpoints'...
[00:15:25] Starting 'doc:api:entities'...
[00:15:25] Starting 'doc:styles'...
[00:15:29] Finished 'build:client:styles' after 3.46 s
Error: EMFILE: too many open files, open '/home/aqz/misskey/src/client/docs/api/endpoints/style.styl'
```
```
[00:15:44] Requiring external module ts-node/register
[00:15:58] Using gulpfile ~/misskey/gulpfile.ts
[00:15:58] Starting 'build:ts'...
[00:15:59] Starting 'build:copy:views'...
[00:15:59] Starting 'build:client:script'...
[00:15:59] Starting 'build:client:styles'...
[00:15:59] Starting 'doc:docs'...
[00:15:59] Starting 'doc:api:endpoints'...
[00:15:59] Starting 'doc:api:entities'...
[00:15:59] Starting 'doc:styles'...
[00:16:00] Finished 'build:client:styles' after 1.43 s
Error: /home/aqz/misskey/src/client/docs/api/style.styl:10:66
    6| 
    7| 	.name
    8| 	.type
    9| 	.optional
   10| 		font-family Consolas, 'Courier New', Courier, Monaco, monospace
------------------------------------------------------------------------^
   11| 
   12| 

EMFILE: too many open files, open '/home/aqz/misskey/node_modules/stylus/lib/functions/index.styl'

    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.readFileSync (fs.js:565:33)
(以下略)
```
----

OS: Ubuntu 18.04 LTS
Node.js: 10.4.1
npm: 6.1.0

**Comment by 2vg** [comment]
ファイルディスクリプタの制限値を上げていけ👊
```
ulimit -n 65535
```

**Comment by syuilo** [comment]
制限を上げてもらう以外に解決策ないしね
別にバグというわけでもないだろうし

**Comment by tamaina** [comment]
`ulimit -n 65535`しても2048までしか上がらないんですよね……

**Comment by 2vg** [comment]
sysctl.conf案件じゃね

**Comment by AyaMorisawa** [comment]
Closed as this is not a problem with Misskey
