### ISSUE TITLE
Build error code: 137  signal: null on Digital Ocean droplet

### ISSUE THREAD

**Issue by zwebmedia** [misskey-dev/misskey#2087]
This is a very elegant script and I am excited to get it installed thank you Syuilo. I am working through the install procedure on Digital Ocean $5 droplet. I used one click install Ubuntu 16.04 LEMP stack. The build is completing, but then the process gets killed with error 137, signal null.  The console shows:

```
root@MissKey01-on-trllion:/home/misskey/misskey# npm run build

> misskey@5.10.0 build /home/misskey/misskey
> webpack && gulp build

(node:24334) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
  yes we can [====================] 98% (98/100) 52.0s
Build completed in 52.122s

Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! misskey@5.10.0 build: `webpack && gulp build`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the misskey@5.10.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-03T23_06_27_562Z-debug.log
`
```
The contents of the log file are as follows:

```
 File: /root/.npm/_logs/2018-08-03T23_06_27_562Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle misskey@5.10.0~prebuild: misskey@5.10.0
6 info lifecycle misskey@5.10.0~build: misskey@5.10.0
7 verbose lifecycle misskey@5.10.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle misskey@5.10.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/misskey/misskey/node_modules/.bin:/usr/local/sb$
9 verbose lifecycle misskey@5.10.0~build: CWD: /home/misskey/misskey
10 silly lifecycle misskey@5.10.0~build: Args: [ '-c', 'webpack && gulp build' ]
11 silly lifecycle misskey@5.10.0~build: Returned: code: 137  signal: null
12 info lifecycle misskey@5.10.0~build: Failed to exec build script
13 verbose stack Error: misskey@5.10.0 build: `webpack && gulp build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid misskey@5.10.0
15 verbose cwd /home/misskey/misskey
16 verbose Linux 4.4.0-109-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 137
22 error misskey@5.10.0 build: `webpack && gulp build`
22 error Exit status 137
23 error Failed at the misskey@5.10.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

```
Additional info:
I am building Misskey under user root because I do get many key not found and file not found errors when building under user 'misskey', such as:

```
misskey@MissKey01-on-trllion:~/misskey$ npm run build

> misskey@5.10.0 build /home/misskey/misskey
> webpack && gulp build

(node:24422) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
  yes we can [====================] 98% (98/100) 60.3s
Build completed in 60.489s

path 'desktop/views/pages/deck/deck.widgets-column.vue' not found
key 'matching.cancel' not found in 'common/views/components/games/reversi/reversi.vue'
path 'desktop/views/components/input-dialog.vue' not found
path 'desktop/views/components/input-dialog.vue' not found
key 'max' not found in 'null'
key 'in-use' not found in 'null'
path 'desktop/views/components/timeline.core.vue' not found
path 'desktop/views/components/users-list.item.vue' not found
key 'less' not found in 'desktop/views/pages/deck/deck.note.vue'
key 'more' not found in 'desktop/views/pages/deck/deck.note.vue'
key 'location' not found in 'desktop/views/pages/deck/deck.note.vue'
path 'desktop/views/pages/deck/deck.notes.vue' not found
path 'desktop/views/pages/deck/deck.notes.vue' not found
path 'desktop/views/pages/deck/deck.notes.vue' not found
path 'desktop/views/pages/deck/deck.notifications.vue' not found
path 'desktop/views/pages/deck/deck.notifications.vue' not found
key 'not-found' not found in 'null'
key 'not-found' not found in 'null'
key 'no-posts-found' not found in 'null'
key 'no-posts-found' not found in 'null'
key 'no-one' not found in 'desktop/views/pages/user-list.users.vue'
key 'last-used-at' not found in 'desktop/views/pages/user/user.vue'
key 'notifications' not found in 'mobile/views/pages/favorites.vue'
key 'followers-of' not found in 'mobile/views/pages/following.vue'
key 'title' not found in 'mobile/views/pages/selectdrive.vue'
key 'matching.cancel' not found in 'common/views/components/games/reversi/reversi.vue'
key 'delete' not found in 'mobile/views/components/drive.file-detail.vue'
key 'load-more' not found in 'mobile/views/components/notes.vue'
key 'more' not found in 'mobile/views/pages/favorites.vue'
key 'no-users' not found in 'mobile/views/pages/followers.vue'
key 'no-users' not found in 'mobile/views/pages/following.vue'
path 'mobile/views/pages/home.timeline.vue' not found
key 'no-posts-found' not found in 'null'
key 'no-posts-found' not found in 'null'
path 'mobile/views/widgets/activity.vue' not found
key 'matching.cancel' not found in 'common/views/components/games/reversi/reversi.vue'
key 'matching.cancel' not found in 'common/views/components/games/reversi/reversi.vue'
Hash: a47ea97a2750e8fccd4d
Version: webpack 4.16.3
Time: 60503ms
Built at: 2018-08-03 23:35:28
                Asset      Size   Chunks             Chunk Names
   auth.1.0.7828.-.js  4.21 MiB     auth  [emitted]  auth
desktop.1.0.7828.-.js  7.76 MiB  desktop  [emitted]  desktop
    dev.1.0.7828.-.js  5.13 MiB      dev  [emitted]  dev
 mobile.1.0.7828.-.js  6.96 MiB   mobile  [emitted]  mobile
     sw.1.0.7828.-.js  10.8 KiB       sw  [emitted]  sw
Entrypoint desktop = desktop.1.0.7828.-.js
Entrypoint mobile = mobile.1.0.7828.-.js
Entrypoint dev = dev.1.0.7828.-.js
Entrypoint auth = auth.1.0.7828.-.js
Entrypoint sw = sw.1.0.7828.-.js
[./src/client/app/auth/script.ts] 611 bytes {auth} [built]
[./src/client/app/common/views/pages/follow.vue] 1.19 KiB {desktop} {mobile} [built]
[./src/client/app/desktop/api/choose-drive-file.ts] 970 bytes {desktop} [built]
[./src/client/app/desktop/api/choose-drive-folder.ts] 580 bytes {desktop} [built]
[./src/client/app/desktop/api/dialog.ts] 541 bytes {desktop} [built]
[./src/client/app/desktop/api/input.ts] 620 bytes {desktop} [built]
[./src/client/app/desktop/api/notify.ts] 319 bytes {desktop} [built]
[./src/client/app/desktop/api/post.ts] 643 bytes {desktop} [built]
[./src/client/app/desktop/api/update-avatar.ts] 4.07 KiB {desktop} [built]
[./src/client/app/desktop/script.ts] 5.81 KiB {desktop} [built]
[./src/client/app/dev/script.ts] 1.19 KiB {dev} [built]
[./src/client/app/init.ts] 5.51 KiB {desktop} {mobile} {dev} {auth} [built]
[./src/client/app/mobile/script.ts] 4.64 KiB {mobile} [built]
[./src/client/app/mobile/views/pages/messaging-room.vue] 1.11 KiB {mobile} [built]
[./src/client/app/sw.js] 1.34 KiB {sw} [built]
    + 2648 hidden modules

```

I am quite new to Linux and I am probably doing something wrong with user or permissions. Any recommendation is much appreciated. I can provide additional info if needed. Thank you again in advance for your help.

Edit: I checked droplet resource usage. Memory usage goes near 60% during build, the other metric are well below that, so I do not think this is a resource issue.

**Comment by syuilo** [comment]
Thank you for your reporting.
I do not know how to solve 137 errors.
'key not found' error is not a problem!

**Comment by zwebmedia** [comment]
Thank you Syuilo. Based on your info, I changed back to user misskey. The build is completing but there was an error about missing file/folder:

`Error: ENOENT: no such file or directory, scandir '/home/misskey/misskey/node_modules/node-sass/vendor'`

Yes, the error was correct, I had no vendor folder. After searching, I found this thread. Apparently there is an incompatibility with node-sass and Ubuntu:

https://github.com/sass/node-sass/issues/1579

I re-installed node-sass with:

```
npm install node-sass
npm rebuild node-sass
```
I am making progress. Now the build completes and I am getting an error: out of memory. 

`FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory`

Next I will try  to increase droplet memory. Will post again later. Thank you.

**Comment by syuilo** [comment]
We apologize for inconvenience. Good luck! 👍

**Comment by zwebmedia** [comment]
OK and thanks! I did not need to increase the droplet size. For any other users benefit, I needed to:
- update, install, rebuild node-sass as user misskey.
- install a missing Node module disk-usage.
- Mongo service was not running. I started it.
- I had to set NODE_ENV to 'production'. ($ export NODE_ENV=production) 

Now I can start misskey service, but still have error that MongoDB is not found. Here is console output where I verify that Mongo is running (V3.2.20), then start Misskey, and I still get error Mongo not found.:

```
root@MissKey01-on-trllion:/home/misskey/misskey# mongod --version
db version v3.2.20
git version: a7a144f40b70bfe290906eb33ff2714933544af8
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
root@MissKey01-on-trllion:/home/misskey/misskey# npm start

> misskey@5.10.0 start /home/misskey/misskey
> node ./built

[03:17:54 INFO] Welcome to Misskey!
[03:17:54 INFO] [Deps] Node.js v8.11.3
[03:17:54 INFO] [Machine] Hostname: MissKey01-on-trllion
[03:17:54 INFO] [Machine] Platform: linux
[03:17:54 INFO] [Machine] Architecture: x64
[03:17:54 INFO] [Machine] CPU: 1 core
[03:17:54 INFO] [Machine] MEM: 1.0GB (available: 0.2GB)
[03:17:54 INFO] [Env] NODE_ENV: production
[03:17:54 INFO] [Env] You have root privileges
[03:17:54 WARN] [Deps] MongoDB not found
[03:17:54 WARN] [Deps] Regexp used for version check of MongoDB is probably messed up
[03:17:54 INFO] [Deps] Redis 4.0.10 found
[03:17:54 INFO] [Config] Loaded
[03:17:54 ERROR] Port 80 is already in use
[03:17:54 INFO] The process is going to exit with code 1


```
Thanks so much for any help you can provide.

**Comment by syuilo** [comment]
Cool! What is the version of your MongoDB?

**Comment by syuilo** [comment]
Misskey requires MongoDB 3.6 or later :)

**Comment by zwebmedia** [comment]
Thanks, fantastic! Let me work on this and I will report the result a little later thanks again.

**Comment by syuilo** [comment]
👍👍👍

**Comment by zwebmedia** [comment]
Yes correct, misskey now finds MongoDB 3.6.6. Only one more error to go:

`[ERROR] Port 80 is already in use`

I see this excellent info about Nginx config here:

https://github.com/syuilo/misskey/issues/1934

I will work on this now, and please let me know of any other ideas about this last error, thank you again.

**Comment by zwebmedia** [comment]
Sorry to inform, still no success :(. I am confused about which user to start misskey. If I start misskey under user misskey, I get Linux error that using ports below 1,000 requires root privileges. So, I tried to start misskey under user root. Then I get error message that port 80 is already in use. 

`netstat -tupln`
```
root@MissKey01-on-trllion:/home/misskey/misskey# netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      29775/nginx -g daem
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      9189/mongod
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      23976/mysqld
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      20790/redis-server
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      29775/nginx -g daem
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      24141/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      24141/sshd
```
Yes of course, port 80 is in use. Nginx is listening to port 80 for http traffic. The only way to get rid of that error is to change nginx config to listen to port 81 or some other port for http traffic.

May I ask what I am doing wrong? What user should I use to start misskey? And how to fix port 80 already used error? Is it necessary to do some port forwarding to get this to work? Thanks for your assistance always.

**Comment by syuilo** [comment]
Misskey needs to be started as root. When using with Nginx, it is necessary to perform port forwarding.

**Comment by zwebmedia** [comment]
OK awesome, thanks for the info. I'm back to work and will update you later thanks again.

**Comment by syuilo** [comment]
Please try remove this line: `proxy_set_header Proxy "";`

**Comment by zwebmedia** [comment]
Thank you for recommendation. I removed that line, and restarted Nginx, same problem "Bad Gateway", Same error message in Nginx error log file:

`2018/08/05 11:01:24 [error] 25551#25551: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 125.25.36.34, server: trillion.city, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9584/", host: "trillion.city"
`

**Comment by zwebmedia** [comment]
Hi Guys, I tried everything and nothing seems to work. 

There are three major systems here: Nginx config, UFW firewall, and Misskey itself. All three must be correct for this to work. This is a very complex system to troubleshoot. Can we come up with a simplified system to verify each system independent of the others?

I noticed that the error message I am getting changes from "Bad Gateway" to "Internal Server Error" when I disable the firewall. Occasionally when I am testing settings I get error "Too many open files".

Can I use curl to access Misskey directly over localhost (bypass Nginx and firewall for testing) and verify that it is working correctly? How can I do that? 

Next, I would want to use Nginx without SSL and a simple flow through and get that working. Then enable proxy and get that working. Then enable SSL and get that working. Finally, turn on the firewall and get that working.

Can anyone help me with step 1? Anyone with a working setup could easily answer these questions. How to access Misskey with curl over localhost and what is the expected result? As always, thanks in advance for your assistance.

**Comment by mei23** [comment]
@zwebmedia
To check working correctly without Nginx
Please try `curl -X POST -w '\n' -v 'http://localhost:9584/api/meta'`
```
$ curl -X POST -w '\n' -v 'http://localhost:9584/api/meta'
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9584 (#0)
> POST /api/meta HTTP/1.1
> Host: localhost:9584
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Vary: Accept-Encoding, Origin
< strict-transport-security: max-age=15552000; preload
< Content-Type: application/json; charset=utf-8
< Content-Length: 246
< Date: Mon, 06 Aug 2018 10:19:38 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
{"maintainer":{"name":"maintainer","url":"http://example.com/"},"version":"4.16.1","clientVersion":"1.0.6952",
"secure":false,"machine":"xxx","os":"linux","node":"v10.8.0","cpu":{"model":"Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz","cores":1}}
```

**Comment by zwebmedia** [comment]
@mei23 thank you so much this is excellent info. There is definitely something wrong with my Misskey build, perhaps out of memory, I will increase droplet memory and try again.  thanks again, very helpful info.
