### ISSUE TITLE
follow requestを送ると、MongoErrorが発生する

### ISSUE THREAD

**Issue by xps2** [misskey-dev/misskey#2430]
# Summary

follow requestを送ると、MongoErrorが発生する

# Expected Behavior

MongoErrorが発生しない

# Actual Behavior

MongoError: E11000 duplicate key error collection: misskey.following index: followerId_1_followeeId_1 dup key:

# Steps to Reproduce
1. フォローしたいユーザのページへ遷移する
2. フォローを押下する

# Environment

Node.js v10.9.0
MongoDB v4.0.1

**Comment by syuilo** [comment]
既にフォローしているっぽいですね

**Comment by xps2** [comment]
フォローしたことのない人をフォローしても発生しますね…

**Comment by xps2** [comment]
```
2018-08-23T16:27:14.348Z misskey:activitypub Creating the Person: https://comm.cx/users/xps2
SLOW API CALL DETECTED: users/show (8573.393705010414ms)
2018-08-23T16:27:31.533Z misskey:limitter @xps2 following/create max remaining: 96
2018-08-23T16:27:31.539Z misskey:activitypub:deliver --> https://comm.cx/users/xps2/inbox
2018-08-23T16:27:36.323Z misskey:activitypub:deliver https://comm.cx/users/xps2/inbox --> 202
2018-08-23T16:27:37.001Z misskey:queue:inbox { id: 'https://comm.cx/users/xps2#accepts/follows/544',
  type: 'Accept',
  actor: 'https://comm.cx/users/xps2',
  object:
   { id: 'https://comm.cx/bcf7d44e-021c-40f8-921a-aacf125859ee',
     type: 'Follow',
     actor: 'https://misskey.xps2.net/users/5b7ae24c41cfaf10a4c5ad1b',
     object: 'https://comm.cx/users/xps2' } }
2018-08-23T16:27:37.004Z misskey:activitypub Accept: https://comm.cx/users/xps2#accepts/follows/544
{ MongoError: E11000 duplicate key error collection: misskey.following index: followerId_1_followeeId_1 dup key: { : ObjectId('5b7ae24c41cfaf10a4c5ad1b'), : ObjectId('5b7ee0694ac8db2484ea359c') 
    at Function.MongoError.create (/home/misskey/misskey/node_modules/monk/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/misskey/misskey/node_modules/monk/node_modules/mongodb/lib/utils.js:139:22)
    at /home/misskey/misskey/node_modules/monk/node_modules/mongodb/lib/collection.js:668:23
    at handleCallback (/home/misskey/misskey/node_modules/monk/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/home/misskey/misskey/node_modules/monk/node_modules/mongodb/lib/bulk/ordered.js:421:14)
    at /home/misskey/misskey/node_modules/monk/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
  name: 'MongoError',
  message:
   'E11000 duplicate key error collection: misskey.following index: followerId_1_followeeId_1 dup key: { : ObjectId(\'5b7ae24c41cfaf10a4c5ad1b\'), : ObjectId(\'5b7ee0694ac8db2484ea359c\') }',
  driver: true,
  code: 11000,
  index: 0,
  errmsg:
   'E11000 duplicate key error collection: misskey.following index: followerId_1_followeeId_1 dup key: { : ObjectId(\'5b7ae24c41cfaf10a4c5ad1b\'), : ObjectId(\'5b7ee0694ac8db2484ea359c\') }',
  getOperation: [Function],
  toJSON: [Function],
  toString: [Function] }
```

**Comment by xps2** [comment]
よくわからんが、8.8.0にアップデートしたら直った??
