### ISSUE TITLE
can't find index with key:{ date: -1 } error in my server

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2787]
# Summary
I have setup my server, but it claims `can\'t find index with key:{ date: -1 }` and stops.

# Expected Behavior
No error claimed.

# Actual Behavior
Outputs `can\'t find index with key:{ date: -1 }` and stops.

# Steps to Reproduce
1. Clone the `master` branch of Misskey. (Not stable version)
2. Setup a server.
3. `sudo npm start` at `/home/misskey/misskey`.

# Environment
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

# Log
```
- Starting workers [                              ] 0 / 3 (0 %)[11:27:58 INFO] [MongoDB] Connectivity confirmed
| Starting workers [**********                    ] 1 / 3 (33 %){ MongoError: can't find index with key:{ date: -1 }
    at Function.MongoError.create (/home/misskey/misskey/node_modules/monk/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/misskey/misskey/node_modules/monk/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/home/misskey/misskey/node_modules/monk/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/home/misskey/misskey/node_modules/monk/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/home/misskey/misskey/node_modules/monk/node_modules/mongodb-core/lib/connection/connection.js:363:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'MongoError',
  message: 'can\'t find index with key:{ date: -1 }',
  nIndexesWas: 2,
  ok: 0,
  errmsg: 'can\'t find index with key:{ date: -1 }' }
```

**Comment by ghost** [comment]
Thank you very much! This issue is resolved.

And now I face the another question: https://github.com/syuilo/misskey/issues/2791
