### ISSUE TITLE
Build fails when NODE_ENV is "production"

### ISSUE THREAD

**Issue by incognico** [misskey-dev/misskey#2918]
# Summary
Build fails when NODE_ENV is "production"
(It works fine when env is not production)

# Actual Behavior
```
[11:47:37] Requiring external module ts-node/register
[11:47:39] Using gulpfile /usr/home/misskey/misskey/gulpfile.ts
[11:47:39] Starting 'build:ts'...
[11:47:39] Starting 'build:copy:views'...
[11:47:39] Starting 'build:copy:lang'...
[11:47:39] Starting 'build:client:script'...
[11:47:39] Starting 'build:client:styles'...
[11:47:39] Starting 'doc'...
[11:47:39] Finished 'build:client:styles' after 437 ms
[11:47:39] Finished 'build:copy:views' after 532 ms
[11:47:39] Finished 'build:client:script' after 527 ms
[11:47:39] Starting 'copy:client'...
[11:47:39] Finished 'doc' after 619 ms
Error: spawn /usr/home/misskey/misskey/node_modules/optipng-bin/vendor/optipng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! misskey@10.19.0 build: `webpack && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the misskey@10.19.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/misskey/.npm/_logs/2018-10-16T09_47_39_896Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle misskey@10.19.0~prebuild: misskey@10.19.0
6 info lifecycle misskey@10.19.0~build: misskey@10.19.0
7 verbose lifecycle misskey@10.19.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle misskey@10.19.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/home/misskey/misskey/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/
sbin:/usr/local/bin:/home/misskey/bin
9 verbose lifecycle misskey@10.19.0~build: CWD: /usr/home/misskey/misskey
10 silly lifecycle misskey@10.19.0~build: Args: [ '-c', 'webpack && gulp build' ]
11 silly lifecycle misskey@10.19.0~build: Returned: code: 1  signal: null
12 info lifecycle misskey@10.19.0~build: Failed to exec build script
13 verbose stack Error: misskey@10.19.0 build: `webpack && gulp build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid misskey@10.19.0
15 verbose cwd /usr/home/misskey/misskey
16 verbose FreeBSD 11.2-RELEASE
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error misskey@10.19.0 build: `webpack && gulp build`
22 error Exit status 1
23 error Failed at the misskey@10.19.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

# Steps to Reproduce
1. NODE_ENV='production' npm run build

# Environment
FreeBSD 11.2

**Comment by syuilo** [comment]
Thank you for your reporting.

This issue seems to be related to the following issue:
https://github.com/panteng/wechat-h5-boilerplate/issues/5

Please check it!

**Comment by incognico** [comment]
Thanks, it worked!
