### ISSUE TITLE
configに古い形式のServiceWorkerの設定があるとエラーになる

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#3683]
# Summary
configにcamelcaseでない設定が残っていると起動時にエラーになってしまう
```
# ServiceWorkerの設定
sw:
  # VAPIDの公開鍵
  public_key: ...

  # VAPIDの秘密鍵
  private_key: ...
```
```
Error: No key set vapidDetails.publicKey
    at Object.validatePublicKey (misskey/node_modules/web-push/src/vapid-helper.js:88:11)
    at Object.WebPushLib.setVapidDetails (misskey/node_modules/web-push/src/web-push-lib.js:61:17)
```
breaking change扱いで変更を促すか、エラーにならないようにしたほうが良さそう。

# Environment
develop

**Comment by syuilo** [comment]
そのうちServiceWorkerの設定はその他の設定と同様にデータベースに保存するようにするのでそのときに良い感じにやっておきます
