### ISSUE TITLE
TypeError: Cannot read property '_id' of null

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3729]
# Summary

A lot of errors in console as follows:
```
TypeError: Cannot read property '_id' of null
at user_1.default.update.$set.pinnedNoteIds.featuredNotes.map.note (/home/misskey/misskey/built/remote/activitypub/models/person
.js:363:59)
at Array.map (<anonymous>)
at updateFeatured (/home/misskey/misskey/built/remote/activitypub/models/person.js:363:42)
at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property '_id' of null
at user_1.default.update.$set.pinnedNoteIds.featuredNotes.map.note (/home/misskey/misskey/built/remote/activitypub/models/person
.js:363:59)
at Array.map (<anonymous>)
at updateFeatured (/home/misskey/misskey/built/remote/activitypub/models/person.js:363:42)
at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property '_id' of null
at user_1.default.update.$set.pinnedNoteIds.featuredNotes.map.note (/home/misskey/misskey/built/remote/activitypub/models/person
.js:363:59)
at Array.map (<anonymous>)
at updateFeatured (/home/misskey/misskey/built/remote/activitypub/models/person.js:363:42)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have no idea how to reproduce, nor do I know what could be causing it, hopefully the errors themselves are enough? 

# Expected Behavior

Not have those errors

# Actual Behavior

Lots of errors

**Comment by mei23** [comment]
It seems that you have failed to fetch the pinned posts of remote users.
I do not need to worry much.

**Comment by ibrokemypie** [comment]
Awesome, yeah I assumed it was likely due to someone elses instance being broken, and since misskey didnt crash it didnt seem too important, but an error is an error, and if it is spamming the logs then thats not what you want
