### ISSUE TITLE
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3745]
# Summary

Very long error repeated multiple times with general usage

# Expected Behavior

no error

# Actual Behavior

```
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
at Function.createFromHexString (/home/misskey/misskey/node_modules/monk/node_modules/bson/lib/bson/objectid.js:312:11)
at Object.exports.id (/home/misskey/misskey/node_modules/monk/lib/helpers.js:13:45)
at /home/misskey/misskey/node_modules/monk/lib/helpers.js:39:29
at Array.forEach (<anonymous>)
at Object.cast (/home/misskey/misskey/node_modules/monk/lib/helpers.js:30:22)
at Manager.cast (/home/misskey/misskey/node_modules/monk/lib/manager.js:316:31)
at /home/misskey/misskey/node_modules/monk-middleware-cast-ids/index.js:16:44
at Array.forEach (<anonymous>)
at /home/misskey/misskey/node_modules/monk-middleware-cast-ids/index.js:14:22
at /home/misskey/misskey/node_modules/monk-middleware-options/index.js:41:14
at /home/misskey/misskey/node_modules/monk-middleware-query/index.js:12:14
at Collection.findOne (/home/misskey/misskey/node_modules/monk/lib/collection.js:234:5)
at router.get (/home/misskey/misskey/built/server/web/index.js:131:39)
at dispatch (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
at next (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
at /home/misskey/misskey/node_modules/koa-router/lib/router.js:346:16
at dispatch (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
at /home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
at dispatch (/home/misskey/misskey/node_modules/koa-router/lib/router.js:351:31)
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at app.use (/home/misskey/misskey/built/server/web/index.js:36:11)
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at /home/misskey/misskey/node_modules/koa-favicon/index.js:39:14
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at views (/home/misskey/misskey/node_modules/koa-views/src/index.js:55:12)
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at /home/misskey/misskey/node_modules/koa-compose/index.js:34:12
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at dispatch (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
at next (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
at router.get (/home/misskey/misskey/built/server/activitypub.js:61:22)
at dispatch (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
at next (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
at /home/misskey/misskey/node_modules/koa-router/lib/router.js:346:16
at dispatch (/home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
at /home/misskey/misskey/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
at dispatch (/home/misskey/misskey/node_modules/koa-router/lib/router.js:351:31)
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at /home/misskey/misskey/node_modules/koa-mount/index.js:52:32
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at /home/misskey/misskey/node_modules/koa-mount/index.js:52:32
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at app.use (/home/misskey/misskey/built/server/index.js:44:15)
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at /home/misskey/misskey/node_modules/koa-compress/index.js:38:11
at dispatch (/home/misskey/misskey/node_modules/koa-compose/index.js:42:32)
at /home/misskey/misskey/node_modules/koa-compose/index.js:34:12
at Application.handleRequest (/home/misskey/misskey/node_modules/koa/lib/application.js:151:12)
at Server.handleRequest (/home/misskey/misskey/node_modules/koa/lib/application.js:133:19)
at Server.emit (events.js:187:15)
at parserOnIncoming (_http_server.js:672:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

# Steps to Reproduce
make a post? not sure

# Environment

on misskey itself

**Comment by acid-chicken** [comment]
Memo: maybe here

https://github.com/syuilo/misskey/blob/1395cf89cee2916cf5e2a1af52357707222b6afd/src/server/web/index.ts#L150-L164
