### ISSUE TITLE
Use a feature of Node v11.7.0 to extract a public key

### ISSUE THREAD

**Issue by akihikodaki** [misskey-dev/misskey#3921]
# Summary
Here is a good news: Node.js v11.7.0 now has a feature to extract a public key. It was introduced with the following pull request:
https://github.com/nodejs/node/pull/25217

The API allowing to extract a public key is `crypto.createPublicKey(key)`.
https://nodejs.org/api/crypto.html#crypto_crypto_createpublickey_key

It effectively replaces the functionality of `src/crypto_key.cc`, which I introduced in #1303 and a pull request recently merged, #3906, updated.

However, please note that the version of Node.js was released today (2019-01-18). You may carefully decide when to make such a change because it may not be widely available yet and some may prefer LTS versions.

# Environment
Node.js v11.7.0

**Comment by JLKM** [comment]
### Should I upgade my node.js?
I have spent a couple of evenings without getting misskey up and running, and some of the errors looks like this one with `crypto key`. Does the solution also match?

##### My setup
- Server: Ubuntu 18.04 LTS
- Node.js latest LTS
- Misskey v. 10.98.3

##### Workaround with no luck
- Setting `allowEmpty: true`
https://github.com/syuilo/misskey/search?q=allowEmpty&unscoped_q=allowEmpty

I would rather not upgrade to node 11.7.0+ as suggested in this issue and [here](https://github.com/syuilo/misskey/pull/3906) and [here](https://github.com/syuilo/misskey/pull/4623). Is there another way out? And a quick one. I would really like to get on with my test of this awesome project as soon as possible.

##### For all those persistent people out there - have some highlights from my error log...

##### It fires up pretty ok
```
[21:40:53] Requiring external module ts-node/register
[21:40:56] Using gulpfile /etc/misskey/gulpfile.ts
[21:40:56] Starting 'build'...
[21:40:56] Starting 'build:ts'...
[21:40:56] Starting 'build:copy'...
[21:40:56] Starting 'build:client'...
[21:40:56] Starting 'doc'...
[21:40:56] Starting 'build:copy:views'...
[21:40:56] Starting '<anonymous>'...
[21:40:56] Starting 'build:client:script'...
[21:40:56] Starting 'build:client:styles'...
[21:40:56] Starting 'copy:client'...
```

But then:

```
[21:40:56] '<anonymous>' errored after 59 ms
[21:40:56] Error: File not found with singular glob: /etc/misskey/build/Release/crypto_key.node (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/etc/misskey/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:277:13)
    at Glob.emit (events.js:189:13)
    at Glob.EventEmitter.emit (domain.js:441:20)
    at Glob._finish (/etc/misskey/node_modules/glob/glob.js:197:8)
    at done (/etc/misskey/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/etc/misskey/node_modules/glob/glob.js:688:12)
    at /etc/misskey/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/etc/misskey/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/etc/misskey/node_modules/glob/glob.js:764:12)
```
...and...
```
[21:40:56] 'build:copy' errored after 118 ms
[21:40:56] 'build' errored after 120 ms
[21:40:56] The following tasks did not complete: build:ts, build:client, doc, build:copy:views, build:client:script, build:client:styles, copy:client
[21:40:56] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! misskey@10.98.3 build: `webpack && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the misskey@10.98.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by acid-chicken** [comment]
You should use `yarn` (my recommendation) or try to execute these commands.

1. `npm install -g node-gyp`
2. `node-gyp configure`
3. `node-gyp build`
