### ISSUE TITLE
ドキュメントにアクセスできない

### ISSUE THREAD

**Issue by YuzuRyo61** [misskey-dev/misskey#4152]
# Summary
ドキュメントにアクセスできない。Internal Server Errorが発生する。

https://misskey.xyz/docs/ja-JP/stream など、他のページにアクセスしても同様。

# Stack trace (on yuzulia.xyz)

```
  TypeError: /home/misskey/misskey/src/docs/article.pug:8
      6| block footer
      7|        p
    > 8|                = i18n('docs.edit-this-page-on-github')
      9|                a(href=src target="_blank")= i18n('docs.edit-this-page-on-github-link')
      10|

  Cannot read property 'ja-JP' of undefined
      at vars.i18n (/home/misskey/misskey/built/server/web/docs.js:55:65)
      at eval (eval at wrap (/home/misskey/misskey/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:252:57)
      at template (eval at wrap (/home/misskey/misskey/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:260:208)
      at /home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:951:16
      at /home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:161:5
      at Promise._execute (/home/misskey/misskey/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:483:18)
      at new Promise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:79:10)
      at promisify (/home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:154:10)
      at exports.pug (/home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:935:10)
      at getPaths.then.paths (/home/misskey/misskey/node_modules/koa-views/src/index.js:42:18)
      at tryCatcher (/home/misskey/misskey/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:694:18)
      at Promise._fulfill (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:638:18)
      at Promise._settlePromise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:582:21)
      at Promise._settlePromise0 (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:694:18)
      at Promise._fulfill (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:638:18)
      at Promise._resolveCallback (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:432:57)
      at Promise._settlePromiseFromHandler (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:524:17)
      at Promise._settlePromise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:694:18)
      at Promise._fulfill (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:638:18)
      at /home/misskey/misskey/node_modules/bluebird/js/release/nodeback.js:42:21
      at FSReqCallback.oncomplete (fs.js:160:5)
```

# Environment
10.82.0
- yuzulia.xyz
- misskey.xyz

**Comment by ibrokemypie** [comment]
also happens on my instance since 10.82.0
https://boopsnoot.gq/docs/ja-JP/api/entities/user
![image](https://user-images.githubusercontent.com/7827846/52333889-74656e00-2a52-11e9-8620-a23515d6e406.png)
```
Error: request error: 404 - undefined
at request.catch.e (/home/misskey/misskey/built/remote/activitypub/resolver.js:49:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: /home/misskey/misskey/src/docs/api/entities/view.pug:13
11|
12|         section
> 13|                 h2= i18n('docs.api.entities.properties')
14|                 +propTable(props)
15|
16|                 if propDefs
Cannot read property 'ja-JP' of undefined
at vars.i18n (/home/misskey/misskey/built/server/web/docs.js:55:65)
at eval (eval at wrap (/home/misskey/misskey/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:292:57)
at template (eval at wrap (/home/misskey/misskey/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:434:208)
at /home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:951:16
at /home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:161:5
at Promise._execute (/home/misskey/misskey/node_modules/bluebird/js/release/debuggability.js:313:9)
at Promise._resolveFromExecutor (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:483:18)
at new Promise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:79:10)
at promisify (/home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:154:10)
at exports.pug (/home/misskey/misskey/node_modules/consolidate/lib/consolidate.js:935:10)
at getPaths.then.paths (/home/misskey/misskey/node_modules/koa-views/src/index.js:42:18)
at tryCatcher (/home/misskey/misskey/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:694:18)
at Promise._fulfill (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:638:18)
at Promise._settlePromise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:582:21)
at Promise._settlePromise0 (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:694:18)
at Promise._fulfill (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:638:18)
at Promise._resolveCallback (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:432:57)
at Promise._settlePromiseFromHandler (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:524:17)
at Promise._settlePromise (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:694:18)
at Promise._fulfill (/home/misskey/misskey/node_modules/bluebird/js/release/promise.js:638:18)
at /home/misskey/misskey/node_modules/bluebird/js/release/nodeback.js:42:21
at FSReqWrap.oncomplete (fs.js:155:5)
```

**Comment by ibrokemypie** [comment]
Confirmed that it is working fine in 10.81.0

**Comment by ibrokemypie** [comment]
still broken on 10.84.0
is there somewhere else we can see docs? it is making client development very difficult

**Comment by mei23** [comment]
#4117 のせいぽい
