### ISSUE TITLE
TypeError: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4289]
# Summary

since updating (from 10.85.1 to 10.86.1), running npm start results in ```TypeError: Cannot read property 'range' of undefined
    at Object.<anonymous> (/home/misskey/misskey/built/server/api/endpoints/instances.js:10:52)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at files.map.f (/home/misskey/misskey/built/server/api/endpoints.js:9:16)
    at Array.map (<anonymous>)```

# Expected Behavior

missky starts

# Actual Behavior

error and misskey doesnt start

# Steps to Reproduce

1. update to 10.86.1
2. start misskey
3.

# Environment

10.15.1, centos 7

**Comment by syuilo** [comment]
Try:
1. `npm run clean`
2. `npm run build`

**Comment by ibrokemypie** [comment]
ah, sorry, that worked, thanks!

**Comment by syuilo** [comment]
👍
