### ISSUE TITLE
DBにLogをinsertする時にMaximum call stack size exceededが発生することがある

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#4420]
# Summary
```
RangeError: Maximum call stack size exceeded
             :
    at /home/misskey/misskey/node_modules/monk/lib/helpers.js:42:18
    at Array.forEach (<anonymous>)
    at cast (/home/misskey/misskey/node_modules/monk/lib/helpers.js:30:22)
    at /home/misskey/misskey/node_modules/monk/lib/helpers.js:42:18
    at Array.forEach (<anonymous>)
    at cast (/home/misskey/misskey/node_modules/monk/lib/helpers.js:30:22)
    at /home/misskey/misskey/node_modules/monk/lib/helpers.js:42:18
    at Array.forEach (<anonymous>)
    at cast (/home/misskey/misskey/node_modules/monk/lib/helpers.js:30:22)
    at /home/misskey/misskey/node_modules/monk/lib/helpers.js:42:18
    at Array.forEach (<anonymous>)
    at Object.cast (/home/misskey/misskey/node_modules/monk/lib/helpers.js:30:22)
    at Manager.cast (/home/misskey/misskey/node_modules/monk/lib/manager.js:316:31)
    at /home/misskey/misskey/node_modules/monk-middleware-cast-ids/index.js:16:44
    at Array.forEach (<anonymous>)
    at /home/misskey/misskey/node_modules/monk-middleware-cast-ids/index.js:14:22
    at /home/misskey/misskey/node_modules/monk-middleware-options/index.js:41:14
    at /home/misskey/misskey/node_modules/monk-middleware-query/index.js:5:16
    at Collection.insert (/home/misskey/misskey/node_modules/monk/lib/collection.js:334:5)
    at Logger.log (/home/misskey/misskey/built/services/logger.js:53:27)
    at Logger.log (/home/misskey/misskey/built/services/logger.js:30:31)
    at Logger.log (/home/misskey/misskey/built/services/logger.js:30:31)
    at Logger.error (/home/misskey/misskey/built/services/logger.js:71:18)
    at request.catch.e (/home/misskey/misskey/built/remote/activitypub/resolver.js:55:28)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

# Expected Behavior
エラーは発生しない

# Actual Behavior
エラーが発生する

# Steps to Reproduce
1. 検索ボックスに存在しないAPオブジェクトのURLを入力する
   `https://mst.m544.net/users/mei23/statuses/101466012251715000` とか

# Environment

**Comment by mei23** [comment]
これは、かなり長いログが出てきて邪魔なのでDB store無効にして対応してます。
コンソールからログが見れる環境ではDB store不要だと思うので、設定で無効にできるといいかも。

**Comment by acid-chicken** [comment]
あーこのバッファ埋め尽くすログこれが原因だったんですか、スッキリしました。

**Comment by mei23** [comment]
v11以降では起きない
