### ISSUE TITLE
Error: ENOENT: no such file or directory, open './built/client/meta.json

### ISSUE THREAD

**Issue by skid9000** [misskey-dev/misskey#4455]
## Summary

The 10.92.1 and 10.92.2 versions of Misskey can't build.

## Expected Behavior
It should build.

## Actual Behavior

`Error: ENOENT: no such file or directory, open './built/client/meta.json'`

## Steps to Reproduce

1. Checkout to the concerned releases.
2. `npm run clean`
3. `npm install`
4. `npm run build`
5. See error

## Environment

I use NVM with nodejs v10.15.2 and npm v6.4.1 on Debian 9.8

**Comment by skid9000** [comment]
[2019-03-08T12_12_46_048Z-debug.log](https://github.com/syuilo/misskey/files/2945757/2019-03-08T12_12_46_048Z-debug.log)

**Comment by syuilo** [comment]
What happens when you run `npm run webpack`?

**Comment by acid-chicken** [comment]
Try `node node_modules/webpack/bin/webpack.js --verbose`.

**Comment by skid9000** [comment]
The full traceback:

```
misskey@mozuku:~/misskey$ node node_modules/webpack/bin/webpack.js --verbose > log.log
  yes we can [====================] 100% (100/100) 34.1sBuild completed in 34.096s

Error: ENOENT: no such file or directory, open './built/client/meta.json'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at module.exports.plugins.WebpackOnBuildPlugin (/home/misskey/misskey/webpack.config.ts:133:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (/home/misskey/misskey/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/misskey/misskey/node_modules/webpack/lib/Compiler.js:228:21)
    at hooks.afterCompile.callAsync.err (/home/misskey/misskey/node_modules/webpack/lib/Compiler.js:556:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/misskey/misskey/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/misskey/misskey/node_modules/webpack/lib/Compiler.js:553:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/misskey/misskey/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/home/misskey/misskey/node_modules/webpack/lib/Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/misskey/misskey/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/home/misskey/misskey/node_modules/webpack/lib/Compilation.js:1314:32)
    at _err0 (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)
    at taskRunner.run (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/index.js:319:9)
    at step (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/TaskRunner.js:83:9)
    at done (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/TaskRunner.js:94:30)
    at boundWorkers (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/TaskRunner.js:99:13)
    at TaskRunner.boundWorkers (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/TaskRunner.js:68:11)
    at enqueue (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:14)
    at tasks.forEach (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/TaskRunner.js:109:9)
    at Array.forEach (<anonymous>)
    at TaskRunner.run (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:11)
    at TerserPlugin.optimizeFn (/home/misskey/misskey/node_modules/terser-webpack-plugin/dist/index.js:225:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/home/misskey/misskey/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/home/misskey/misskey/node_modules/webpack/lib/Compilation.js:1309:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/misskey/misskey/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/home/misskey/misskey/node_modules/webpack/lib/Compilation.js:1305:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/misskey/misskey/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/misskey/misskey/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/misskey/misskey/node_modules/webpack/lib/Compilation.js:1242:27)
```

**Comment by syuilo** [comment]
同じ現象が発生している方がほかにもいますね
https://misskey.xyz/notes/5c8262465c95600027d6794f

**Comment by syuilo** [comment]
私のコンピュータでは再現できない

**Comment by skid9000** [comment]
NB: Misskey build correctly on the 10.92.0 release 🤔

**Comment by YuzuRyo61** [comment]
Try this:
```npm run cleanall``` -> ```npm install``` -> ```NODE_ENV=production npm run build```

**Comment by acid-chicken** [comment]
**It's just a guess,** but I think Misskey 10.92.1 and later are required Node.js v11.

**Comment by YuzuRyo61** [comment]
おそらくnode_modulesとかの依存絡みでエラーが起きてたのかも・・・。

**Comment by skid9000** [comment]
I will test all of that in approximately one hour.
Node 11 should be easy to setup with nvm ^^'

**Comment by mei23** [comment]
> It's just a guess, but I think Misskey 10.92.1 and later are required Node.js v11.

v10でも動くみたいです
ただバージョン問わず 10.92.0 => 10.92.1 で依存関係が変になるみたいです

**Comment by acid-chicken** [comment]
Hmm, how about `npm prune`?

**Comment by skid9000** [comment]
Ok so after the cleanall, the prune, and the migration to Node11, it works now, thanks everyone :)
