### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by CGsama** [misskey-dev/misskey#4826]
## 💡 Summary

Can not build instance

## 🙂 Expected Behavior

Expect build success

## ☹️ Actual Behavior

build with error

## 📝 Steps to Reproduce

1. Create ubuntu 18.04 instance on aws
2. follow installation guide
3. error when execute NODE_ENV=production npm run build

## 📌 Environment

ubuntu 18.04
error log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.7.0
3 info using node@v11.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle misskey@11.7.0~prebuild: misskey@11.7.0
6 info lifecycle misskey@11.7.0~build: misskey@11.7.0
7 verbose lifecycle misskey@11.7.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle misskey@11.7.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/misskey/misskey/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
9 verbose lifecycle misskey@11.7.0~build: CWD: /home/misskey/misskey
10 silly lifecycle misskey@11.7.0~build: Args: [ '-c', 'webpack && gulp build' ]
11 silly lifecycle misskey@11.7.0~build: Returned: code: 137  signal: null
12 info lifecycle misskey@11.7.0~build: Failed to exec build script
13 verbose stack Error: misskey@11.7.0 build: `webpack && gulp build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid misskey@11.7.0
15 verbose cwd /home/misskey/misskey
16 verbose Linux 4.15.0-1032-aws
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v11.15.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 137
22 error misskey@11.7.0 build: `webpack && gulp build`
22 error Exit status 137
23 error Failed at the misskey@11.7.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by acid-chicken** [comment]
It seems the builder was killed by Linux OOM Killer. Please increase RAM size or swapfile size.

**Comment by CGsama** [comment]
I already have 1G ram and 2G swap, do I need more? Thanks

**Comment by acid-chicken** [comment]
Yes, you should increase the swapfile size at least 2GB. On my VPS, The build was failed when the swapfile size is 2GB and fixed it when the swapfile size is increased to 4GB.

**Comment by acid-chicken** [comment]
@syuilo I think this information should be documented to the installation guide.

**Comment by CGsama** [comment]
Yes that solves the build problem! Thx a lot!
