### ISSUE TITLE
After migration, misskey fails to run with QueryFailedError: column Meta.pinnedUsers does not exist

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#4954]
## 💡 Summary

after migrating then checking out to master and running, misskey fails complaining abou ta missing column

## 🙂 Expected Behavior

misskey runs

## ☹️ Actual Behavior

```
QueryFailedError: column Meta.pinnedUsers does not exist
    at new QueryFailedError (/home/misskey/misskey/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/home/misskey/misskey/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:174:38)
    at Query.handleError (/home/misskey/misskey/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/home/misskey/misskey/node_modules/pg/lib/client.js:194:17)
    at Connection.emit (events.js:196:13)
    at Socket.<anonymous> (/home/misskey/misskey/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  message: 'column Meta.pinnedUsers does not exist',
  name: 'QueryFailedError',
  length: 115,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '610',
  internalPosition: undefined,
  internalQuery: undefined,
```

## 📝 Steps to Reproduce

1. run migration steps
2. attempt to run misskey

## 📌 Environment

centos

**Comment by syuilo** [comment]
Have you tried `npm run migrate`?

**Comment by ibrokemypie** [comment]
yes, checked out migration branch, ran npm run clean, npm i, npm run init, npm run migrate, then check out master, cleaned, installed, built and npm start

**Comment by sftblw** [comment]
I think the problem is

> checked out migration branch

As I know, migration branch is for v10 to v11, not for v11 to v11.

See
https://github.com/syuilo/misskey/blob/develop/CHANGELOG.md#migration

**Comment by ibrokemypie** [comment]
ah yes that seems to have been the problem, thankyou!

**Comment by syuilo** [comment]
Thank you @sftblw
