### ISSUE TITLE
Failed to init database - mentionedUserIds contains null values

### ISSUE THREAD

**Issue by JLKM** [misskey-dev/misskey#4962]
With Misskey 11.11.1, Ubuntu 18.04 LTS, Nodev11.13.0 and PostgreSQL my instance now fails after hitting `npm run init`

```
Failed to init database
{ QueryFailedError: column "mentionedUserIds" contains null values
    at new QueryFailedError (/etc/misskey/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.callback (/etc/misskey/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:174:38)
    at Query.handleError (/etc/misskey/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/etc/misskey/node_modules/pg/lib/client.js:183:17)
    at Connection.emit (events.js:193:13)
    at Socket.<anonymous> (/etc/misskey/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
  message: 'column "mentionedUserIds" contains null values',
  name: 'QueryFailedError',
  length: 144,
  severity: 'ERROR',
  code: '23502',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'hashtag',
  column: 'mentionedUserIds',
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '4593',
  routine: 'ATRewriteTable',
  query:
   'ALTER TABLE "hashtag" ADD "mentionedUserIds" character varying(32) array NOT NULL',
  parameters: [] }

```
Furthermore the instance saves new posts with no problems. But it seems impossible to save profile info (f.ex. language - which I'm trying to switch to danish, with no luck).

Should I delete some records in PostgreSQL and make a new build?

![billede](https://user-images.githubusercontent.com/18215374/58204149-fdd83d80-7cdb-11e9-893d-a51562360ddf.png)

**Comment by JLKM** [comment]
PROBLEM: `"mentionedUserIds" contains null values`
SOLVED AFTER 1: Empty all tables in PostgreSQL and run a new build + init.
SOLVED AFTER 2: GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO `myMisskeyUser on PostgreSQL`.

STILL NOT SOLVED:
PROBLEM 1: Possible to save instance language setting, but it never gets active.

PROBLEM 2: Impossible to save personal profile settings. Message `Got it` - but no change on page-revisit.

PROBLEM 3: Connecting spinner in lower right corner still present all the time.

**Comment by Johann150** [comment]
This should be fixed in the current version. Please open a new issue if you are still experiencing this issue.
