### ISSUE TITLE
外部にRedisをホスティングしたときにエラーが出る

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#5043]
下記のようなエラーが発生する
ローカルに立てた時は発生せず

```
ERR * [core] ReplyError: Ready check failed: NOAUTH Authentication required.

ERR 1 [core] TypeError: Cannot read property 'stack' of undefined

events.js:170
throw er; // Unhandled 'error' event
^
ReplyError: Ready check failed: ERR max number of clients reached
at parseError (/home/nemo/misskey/node_modules/redis/node_modules/redis-parser/lib/parser.js:193:12)
at parseType (/home/nemo/misskey/node_modules/redis/node_modules/redis-parser/lib/parser.js:303:14)
Emitted 'error' event at:
at RedisClient.on_info_cmd (/home/nemo/misskey/node_modules/redis/index.js:496:14)
at /home/nemo/misskey/node_modules/redis/index.js:535:14
at Object.callbackOrEmit [as callback_or_emit] (/home/nemo/misskey/node_modules/redis/lib/utils.js:89:9)
at /home/nemo/misskey/node_modules/redis/lib/individualCommands.js:157:15
at Object.callbackOrEmit [as callback_or_emit] (/home/nemo/misskey/node_modules/redis/lib/utils.js:89:9)
at RedisClient.return_error (/home/nemo/misskey/node_modules/redis/index.js:706:11)
at JavascriptRedisParser.returnError (/home/nemo/misskey/node_modules/redis/index.js:196:18)
at JavascriptRedisParser.execute (/home/nemo/misskey/node_modules/redis/node_modules/redis-parser/lib/parser.js:572:12)
at Socket.<anonymous> (/home/nemo/misskey/node_modules/redis/index.js:274:27)
at Socket.emit (events.js:193:13)
```

**Comment by rinsuki** [comment]
そこのredisの接続数上限に引っかかってるだけなのでは

**Comment by ghost** [comment]
あっホントだ.....
