### ISSUE TITLE
Migration Problems

### ISSUE THREAD

**Issue by philhoefer** [misskey-dev/misskey#5391]
## 💡 Summary

After some time of negligence I wanted to update my misskey instance and failed.
**Note:** When it failed, I started fiddling with it and tried skipping the failing migrations. Before I tried this it said “1 migrations are already loaded in the database.”, now it's three.

## 🙂 Expected Behavior

Successful migration

## ☹️ Actual Behavior

```
yarn run v1.17.3
$ ts-node ./node_modules/typeorm/cli.js migration:run
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations'
query: SELECT * FROM "migrations" "migrations"
3 migrations are already loaded in the database.
18 migrations were found in the source code.
UsedUsername1563757595828 is the last executed migration. It was executed on Mon Jul 22 2019 03:06:35 GMT+0200 (Central European Summer Time).
15 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: CREATE TYPE "log_level_enum" AS ENUM('error', 'warning', 'info', 'success', 'debug')
query failed: CREATE TYPE "log_level_enum" AS ENUM('error', 'warning', 'info', 'success', 'debug')
error: { error: type "log_level_enum" already exists
    at Connection.parseE (/home/misskey/misskey/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/home/misskey/misskey/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/home/misskey/misskey/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:193:13)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:231:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:154:17)
  name: 'error',
  length: 94,
  severity: 'ERROR',
  code: '42710',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'typecmds.c',
  line: '1135',
  routine: 'DefineEnum' }
query: ROLLBACK
Error during migration run:
{ QueryFailedError: type "log_level_enum" already exists
    at new QueryFailedError (/home/misskey/misskey/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/home/misskey/misskey/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/home/misskey/misskey/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/home/misskey/misskey/node_modules/pg/lib/client.js:211:17)
    at Connection.emit (events.js:193:13)
    at Connection.EventEmitter.emit (domain.js:481:20)
    at Socket.<anonymous> (/home/misskey/misskey/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:193:13)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:295:12)
  message: 'type "log_level_enum" already exists',
  name: 'QueryFailedError',
  length: 94,
  severity: 'ERROR',
  code: '42710',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'typecmds.c',
  line: '1135',
  routine: 'DefineEnum',
  query:
   `CREATE TYPE "log_level_enum" AS ENUM('error', 'warning', 'info', 'success', 'debug')`,
  parameters: [] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 📌 Environment

Debian stable

**Comment by EbiseLutica** [comment]
What the version of misskey did you migrate from?

**Comment by philhoefer** [comment]
Sadly I don't remember.
Since I'm the only user on that instance: is there a way to backup my user data and restore to a fresh installation?

**Comment by u1-liquid** [comment]
You should run `node built/tools/accept-migration Init 1000000000000`
https://github.com/syuilo/misskey/blob/develop/CHANGELOG.md#11240-20190705
