### ISSUE TITLE
DNSレコードはないが /etc/hosts にはあるドメインに配信できない

### ISSUE THREAD

**Issue by argxentakato** [misskey-dev/misskey#5596]
```
Error: ENOTFOUND mrbotchi.test at Lookup._makeNotFoundError (/misskey/node_modules/lookup-dns-cache/src/Lookup.js:299:23) at /misskey/node_modules/lookup-dns-cache/src/Lookup.js:263:38 at /misskey/node_modules/lookup-dns-cache/node_modules/async/dist/async.js:3874:9 at /misskey/node_modules/lookup-dns-cache/node_modules/async/dist/async.js:473:16 at iteratorCallback (/misskey/node_modules/lookup-dns-cache/node_modules/async/dist/async.js:1050:13) at /misskey/node_modules/lookup-dns-cache/node_modules/async/dist/async.js:958:16 at /misskey/node_modules/lookup-dns-cache/node_modules/async/dist/async.js:3871:13 at /misskey/node_modules/lookup-dns-cache/src/Lookup.js:279:32 at /misskey/node_modules/lookup-dns-cache/src/Lookup.js:123:24 at Immediate.<anonymous> (/misskey/node_modules/lookup-dns-cache/src/ResolveTask.js:91:32) at processImmediate (internal/timers.js:439:21) at process.topLevelDomainCallback (domain.js:131:23)
```
開発中のActivitypubサーバー上にあるActorをフォローした際、この様なエラーが出て配信に失敗します。コンテナに入って手動でドメインを解決できることを確認しました。

**Comment by mei23** [comment]
`resolve.conf`に書いてあるDNSサーバーで名前解決出来る必要があるので
`hosts`に書いてあるだけのインスタンスとかには配信できないと思います

**Comment by argxentakato** [comment]
そうなのですか。取得は普通にできるので混乱してしまいました。

**Comment by mei23** [comment]
なお、名前解決できたとしてもhttpsで証明書までしっかりしてないと配信できないはず

**Comment by mei23** [comment]
> なお、名前解決できたとしてもhttpsで証明書までしっかりしてないと配信できないはず

これでちゃんとSSL証明書を取ろうとすると、結局インターネット上にDNSサーバーが必要になってくるので…
私はインターネット上にDNSサーバーを用意して、証明書取得時はグローバルアドレスを登録, テスト時はプライベートアドレスを登録 のようにしています。
