### ISSUE TITLE
Node.js 14でビルドできない

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6296]
```
C:\Users\ai\projects\misskey\node_modules\diskusage>if not defined npm_config_node_gyp (node "C:\Users\ai\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\ai\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有効にするには、"/m" 
スイッチを追加してください。
  main.cpp
  diskusage_win.cpp
  win_delay_load_hook.cc
C:\Users\ai\AppData\Local\node-gyp\Cache\14.0.0\x64\node.lib : fatal error LNK1127: ライブラリが壊
れています。
[C:\Users\ai\projects\misskey\node_modules\diskusage\build\diskusage.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ai\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)       
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ai\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ai\projects\misskey\node_modules\diskusage
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! diskusage@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the diskusage@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ai\AppData\Roaming\npm-cache\_logs\2020-04-24T17_35_20_739Z-debug.log 
```

**Comment by mei23** [comment]
CIだとWindowsでもビルドできるぽい
https://github.com/mei23/misskey/runs/616494355?check_suite_focus=true

**Comment by syuilo** [comment]
うーむ

**Comment by syuilo** [comment]
CIはキャッシュが残っててたまたまビルドできてる可能性ないかな

**Comment by mei23** [comment]
CIの v12 / v13 / v14 は別に動いてそう

**Comment by rinsuki** [comment]
逆に @syuilo の環境で
```
C:\Users\ai\AppData\Local\node-gyp\Cache\14.0.0
C:\Users\ai\projects\misskey\node_modules
```
あたり消したら動いたりしない?

**Comment by syuilo** [comment]
node_modules消すと再インストールに4時間くらいかかるから億劫だったけどやってみる

**Comment by syuilo** [comment]
`C:\Users\ai\AppData\Local\node-gyp\Cache\14.0.0`消してみたら成功しました🙏
