### ISSUE TITLE
QueryFailedError: integer out of range

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6807]
## 💡 Summary

```
QueryFailedError: integer out of range
at new QueryFailedError (/misskey/node_modules/typeorm/error/QueryFailedError.js:11:28)
at Query.callback (/misskey/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:187:38)
at Query.handleError (/misskey/node_modules/pg/lib/query.js:128:19)
at Client._handleErrorMessage (/misskey/node_modules/pg/lib/client.js:326:17)
at Connection.emit (events.js:314:20)
at Connection.EventEmitter.emit (domain.js:483:12)
at /misskey/node_modules/pg/lib/connection.js:109:12
at Parser.parse (/misskey/node_modules/pg-protocol/dist/parser.js:40:17)
at Socket.<anonymous> (/misskey/node_modules/pg-protocol/dist/index.js:10:42)
at Socket.emit (events.js:314:20)
at Socket.EventEmitter.emit (domain.js:483:12)
at addChunk (_stream_readable.js:298:12)
at readableAddChunk (_stream_readable.js:273:9)
at Socket.Readable.push (_stream_readable.js:214:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
length: 68,
severity: 'ERROR',
code: '22003',
detail: undefined,
hint: undefined,
position: undefined,
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'int.c',
line: '637',
routine: 'int4pl',
query: 'UPDATE "instance" SET "driveUsage" = "driveUsage" + 56491810 WHERE "host" = $1',
```

## 📌 Environment

Misskey 12.53.0

**Comment by kabili207** [comment]
I'm seeing this issue on 12.55.0
