### ISSUE TITLE
Initializing error: Cannot run yarn run init (yarn run initができません)

### ISSUE THREAD

**Issue by LCinHK** [misskey-dev/misskey#7003]
## 💡 Summary

During installation, Database couldn't be initialized using `yarn run init` 
インストールしていますが、`yarn run init` でデータベースを初期化することができませんでした

## 🙂 Expected Behavior

Database should be initialized and I can go on installation
初期化し、インストレーションを進みます

## ☹️ Actual Behavior
```
yarn run v1.22.10
$ npm run migrate
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1608650242709-0.274286370452828/node but npm is using /www/server/nvm/versions/node/v14.15.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> misskey@12.63.0 migrate /home/misskey/misskey
> ts-node ./node_modules/typeorm/cli.js migration:run

Error during migration run:
error: role "misskey" does not exist
    at Parser.parseErrorMessage (/home/misskey/misskey/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/home/misskey/misskey/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/home/misskey/misskey/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/home/misskey/misskey/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 99,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'miscinit.c',
  line: '675',
  routine: 'InitializeSessionUserId'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! misskey@12.63.0 migrate: `ts-node ./node_modules/typeorm/cli.js migration:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the misskey@12.63.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/misskey/.npm/_logs/2020-12-22T15_18_06_223Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## 📝 Steps to Reproduce
https://github.com/syuilo/misskey/blob/develop/docs/setup.ja.md#6-%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%82%92%E5%88%9D%E6%9C%9F%E5%8C%96

## 📌 Environment
1C 2T 2G RAM VPS
CentOS 7.9.2009
node.js v14.15.3
yarn v1.22.10
Nginx v1.17.10
Redis v6.0.9
PostgreSQL v13.0

**Comment by hinaloe** [comment]
> Please install and **setup** these softwares:
> 
> ### Dependencies 📦
> 
> - Node.js (12.x, 14.x)
> - PostgreSQL (>= 10)
> - Redis

> ## 4. Configure Misskey
> ...
> 
> Edit default.yml

> ```
> Error during migration run:
> error: role "misskey" does not exist
> ```

You have to define a role named `misskey`.

ex:
https://www.postgresql.org/docs/current/sql-createrole.html
https://kb.objectrocket.com/postgresql/how-to-create-a-role-in-postgres-1454

**Comment by LCinHK** [comment]
Thanks, it turned out to be an issue related to the linux panel I was using. Solved after manually configured PostgreSQL
