### ISSUE TITLE
FetchError Parse Error: Header overflow

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7247]
## 💡 Summary
```

FetchError: request to https://misskey/objects/64ff6121-a305-458c-ade9-cbc831bc4226 failed, 
reason: Parse Error: Header overflow
at ClientRequest.<anonymous> (/misskey/node_modules/node-fetch/lib/index.js:1461:11)
at ClientRequest.emit (events.js:314:20)
at ClientRequest.EventEmitter.emit (domain.js:483:12)
at TLSSocket.socketOnData (_http_client.js:481:9)
at TLSSocket.emit (events.js:314:20)
at TLSSocket.EventEmitter.emit (domain.js:483:12)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:272:9)
at TLSSocket.Readable.push (_stream_readable.js:213:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
type: 'system',
errno: 'HPE_HEADER_OVERFLOW',
code: 'HPE_HEADER_OVERFLOW'
```

## 📝 Steps to Reproduce

unavailable since this is from sys log file

## 📌 Environment

Misskey 12.71.0 PostgreSQL 10.15

**Comment by mei23** [comment]
neckbeard.xyz? (I forgot where it was) occasionally returns a large header in the attached image.
I don't plan to deal with it so much, but it may be fixed by starting the process with `NODE_OPTIONS="--max-http-header-size= 65535"` or larger.

**Comment by okpierre** [comment]
Ok will look into it

-Is there a way to see how many users or posts are from that domain?
-How can I remove the domain completely from being fetched?

**Comment by mei23** [comment]
> Is there a way to see how many users or posts are from that domain?

Maybe there is no way to know. 

> How can I remove the domain completely from being fetched?

The domain block may work, but the UI for that feature is now broken.

**Comment by Johann150** [comment]
From what mei23 said I assume this is because neckbeard.xyz sends too large headers, which I would say is a problem of that instance and not of Misskey. That instance also seems to be gone.
