### ISSUE TITLE
Error at Function.createFromInputFallback

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#7309]
## 💡 Summary

```
Error
    at Function.createFromInputFallback (https://example.com/assets/1861.12.73.0.js:2:357566)
    at https://example.com/assets/1861.12.73.0.js:2:377317
    at https://example.com/assets/1861.12.73.0.js:2:377368
    at kt (https://example.com/assets/1861.12.73.0.js:2:377662)
    at bt (https://example.com/assets/1861.12.73.0.js:2:378039)
    at Dt (https://example.com/assets/1861.12.73.0.js:2:378121)
    at r (https://example.com/assets/1861.12.73.0.js:2:354404)
    at ta.parse (https://example.com/assets/1861.12.73.0.js:2:152542)
    at rn (https://example.com/assets/1861.12.73.0.js:2:145936)
    at sn (https://example.com/assets/1861.12.73.0.js:2:146100)
アナリティクスの同意がまだ取れていません。
```

## 🙂 Expected Behavior

No error message

## 📝 Steps to Reproduce

1. Visit `https://example.com/instance`
2. error in console
3. clear error and visit instance. Same error.

## 📌 Environment

Misskey 12.73.0 Chrome 89.0.4389.72

**Comment by mei23** [comment]
~~Probably a custom injected script for misskey.io.
Ask the administrator of that instance as the fork issue cannot be resolved.~~

> アナリティクスの同意がまだ取れていません。

ここの記述はエラー自体と関係なかったぽい

**Comment by cliqsocial** [comment]
@mei23 we have the same problem 

![instanceerror](https://user-images.githubusercontent.com/60059665/110226146-c5a6ec80-7eba-11eb-8d39-b0ff12af86b2.png)

Does this help? https://npmdoc.github.io/node-npmdoc-moment-timezone/build/apidoc.html#apidoc.element.moment-timezone.createFromInputFallback
