### ISSUE TITLE
Update v12.78.0 : Module not found & 502 error

### ISSUE THREAD

**Issue by kazukyakayashi** [misskey-dev/misskey#7474]
## 💡 Summary

It seems that the update of Misskey 12.78.0 is a problem, after the update, Misskey restarts but says it is missing modules if I understand correctly.

## ☹️ Actual Behavior

With `journalctl -u`

```
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.<anonymous> (/home/misskey/misskey/built/queue/index.js:7:17)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 23 14:10:22 Misskey misskey[17021]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 23 14:10:22 Misskey misskey[17021]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.<anonymous> (/home/misskey/misskey/built/server/activitypub.js:16:17)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 23 14:10:22 Misskey misskey[17021]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 23 14:10:22 Misskey misskey[17021]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.<anonymous> (/home/misskey/misskey/built/server/index.js:16:23)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 23 14:10:22 Misskey misskey[17021]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 23 14:10:22 Misskey misskey[17021]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.workerMain (/home/misskey/misskey/built/boot/worker.js:12:11)
Apr 23 14:10:22 Misskey misskey[17021]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Apr 23 14:10:22 Misskey misskey[17021]:     at async Object.default_1 [as default] (/home/misskey/misskey/built/boot/index.js:27:9) {
Apr 23 14:10:22 Misskey misskey[17021]:   code: 'MODULE_NOT_FOUND',
Apr 23 14:10:22 Misskey misskey[17021]:   requireStack: [
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/node_modules/re2/re2.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/misc/check-word-mute.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/services/note/create.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/models/note.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/kernel/create/note.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/kernel/create/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/kernel/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/perform.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/queue/processors/inbox.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/queue/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/server/activitypub.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/server/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/boot/worker.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/boot/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/index.js'
Apr 23 14:10:22 Misskey misskey[17021]:   ]
Apr 23 14:10:22 Misskey misskey[17021]: }
...skipping...
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.<anonymous> (/home/misskey/misskey/built/queue/index.js:7:17)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 23 14:10:22 Misskey misskey[17021]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 23 14:10:22 Misskey misskey[17021]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.<anonymous> (/home/misskey/misskey/built/server/activitypub.js:16:17)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 23 14:10:22 Misskey misskey[17021]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 23 14:10:22 Misskey misskey[17021]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.<anonymous> (/home/misskey/misskey/built/server/index.js:16:23)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 23 14:10:22 Misskey misskey[17021]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 23 14:10:22 Misskey misskey[17021]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 23 14:10:22 Misskey misskey[17021]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 23 14:10:22 Misskey misskey[17021]:     at Object.workerMain (/home/misskey/misskey/built/boot/worker.js:12:11)
Apr 23 14:10:22 Misskey misskey[17021]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Apr 23 14:10:22 Misskey misskey[17021]:     at async Object.default_1 [as default] (/home/misskey/misskey/built/boot/index.js:27:9) {
Apr 23 14:10:22 Misskey misskey[17021]:   code: 'MODULE_NOT_FOUND',
Apr 23 14:10:22 Misskey misskey[17021]:   requireStack: [
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/node_modules/re2/re2.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/misc/check-word-mute.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/services/note/create.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/models/note.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/kernel/create/note.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/kernel/create/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/kernel/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/remote/activitypub/perform.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/queue/processors/inbox.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/queue/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/server/activitypub.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/server/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/boot/worker.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/boot/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/built/index.js',
Apr 23 14:10:22 Misskey misskey[17021]:     '/home/misskey/misskey/index.js'
Apr 23 14:10:22 Misskey misskey[17021]:   ]
Apr 23 14:10:22 Misskey misskey[17021]: }
```

## 📝 Steps to Reproduce

1. Update Misskey v12.77.1 to v12.78.0
2. Start Misskey
3. Error 502 and Module not found

## 📌 Environment

Misskey 12.78.0
Debian 10

**Comment by syuilo** [comment]
try
`npm rebuild`

**Comment by kazukyakayashi** [comment]
Okay it's good, thank you 😁
