### ISSUE TITLE
failed to resolve remote user: QueryFailedError: value too long for type character varying(1024)

### ISSUE THREAD

**Issue by Kusoneko** [misskey-dev/misskey#7548]
## 💡 Summary

Trying to follow a remote user by going to https://misskey.kusoneko.moe/@murabito@lets.bemoe.online
The page returns an error instead of loading the user's profile
I went to https://catgirl.life/@murabito@lets.bemoe.online and it loads properly. I'm unsure if they've updated to 12.82.0 yet or not however.

## 🙂 Expected Behavior

Load the remote user's profile.

## ☹️ Actual Behavior

"An error occured." page with the Retry button and the following logs:

```
1m ago [remote.resolve-user] WebFinger for murabito@lets.bemoe.online
1m ago [remote.resolve-user] return new remote user: murabito@lets.bemoe.online
1m ago [remote.ap] Creating the Person: https://lets.bemoe.online/users/murabito
1m ago [api] failed to resolve remote user: QueryFailedError: value too long for type character varying(1024)
1m ago [remote.ap] QueryFailedError: value too long for type character varying(1024)
```

When running `journalctl -u misskey`, at the end, the following error messages show:

```
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:28 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:28 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:29 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 31 17:45:29 kusoneko.moe misskey[2331401]: Error: invalid person: invalid name
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at validatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:56:20)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at Object.updatePerson (/home/misskey/misskey/built/remote/activitypub/models/person.js:254:17)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at runMicrotasks (<anonymous>)
May 31 17:45:29 kusoneko.moe misskey[2331401]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Which is a weird error message since the user does exist and is loadable on another misskey instance.

## 📝 Steps to Reproduce

1. Go to https://yourmisskeyinstance.tld/@murabito@lets.bemoe.online
2. Receive error page

## 📌 Environment

Misskey v12.82.0
Ubuntu v20.04
Node v14.15.4
PostgreSQL v13
Elasticsearch v7.13.0
Redis v6.2.3

**Comment by okpierre** [comment]
Maybe not Misskey version since catgirl is also on 12.82

`value too long error` has been unresolved for a long time v12.69 v12.74
https://github.com/misskey-dev/misskey/issues/7210
https://github.com/misskey-dev/misskey/issues/7211
https://github.com/misskey-dev/misskey/issues/7369

**Comment by Kusoneko** [comment]
So why does this happen then? On #7210 there seems to be some mention of a fix, increasing 1024 to 2048 or some such, but I'm unfortunately not that far in my understanding of both Japanese and javascript and the entire misskey codebase to be able to manually attempt to fix it.

**Comment by Kusoneko** [comment]
I had a quick look at the postgresql logs and indeed I'm having issues that you also mentioned in your 3 linked issues:

```
2021-05-31 17:56:06.281 UTC [2423456] misskey@misskey ERROR:  value too long for type character varying(1024)
2021-05-31 17:56:06.281 UTC [2423456] misskey@misskey STATEMENT:  INSERT INTO "user_profile"("userId", "location", "birthday", "description", "fields", "lang", "url", "email", "emailVerifyCode", "emailVerified", "emailNotificationTypes",
"twoFactorTempSecret", "twoFactorSecret", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "password", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "pinnedPageId", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes", "userHost") VALUES ($1, $2, $3, $4, $5, DEFAULT, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7) RETURNING "fields", "emailVerified", "emailNotificationTypes", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes"
2021-05-31 17:56:21.179 UTC [2423454] misskey@misskey ERROR:  value too long for type character varying(1024)
2021-05-31 17:56:21.179 UTC [2423454] misskey@misskey STATEMENT:  INSERT INTO "user_profile"("userId", "location", "birthday", "description", "fields", "lang", "url", "email", "emailVerifyCode", "emailVerified", "emailNotificationTypes",
"twoFactorTempSecret", "twoFactorSecret", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "password", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "pinnedPageId", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes", "userHost") VALUES ($1, $2, $3, $4, $5, DEFAULT, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7) RETURNING "fields", "emailVerified", "emailNotificationTypes", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes"
2021-05-31 17:56:28.101 UTC [2423454] misskey@misskey ERROR:  value too long for type character varying(1024)
2021-05-31 17:56:28.101 UTC [2423454] misskey@misskey STATEMENT:  INSERT INTO "user_profile"("userId", "location", "birthday", "description", "fields", "lang", "url", "email", "emailVerifyCode", "emailVerified", "emailNotificationTypes",
"twoFactorTempSecret", "twoFactorSecret", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "password", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "pinnedPageId", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes", "userHost") VALUES ($1, $2, $3, $4, $5, DEFAULT, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7) RETURNING "fields", "emailVerified", "emailNotificationTypes", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes"
2021-05-31 17:56:31.705 UTC [2423454] misskey@misskey ERROR:  value too long for type character varying(1024)
2021-05-31 17:56:31.705 UTC [2423454] misskey@misskey STATEMENT:  INSERT INTO "user_profile"("userId", "location", "birthday", "description", "fields", "lang", "url", "email", "emailVerifyCode", "emailVerified", "emailNotificationTypes",
"twoFactorTempSecret", "twoFactorSecret", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "password", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "pinnedPageId", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes", "userHost") VALUES ($1, $2, $3, $4, $5, DEFAULT, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7) RETURNING "fields", "emailVerified", "emailNotificationTypes", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes"
2021-05-31 17:56:47.992 UTC [2424317] misskey@misskey ERROR:  value too long for type character varying(1024)
2021-05-31 17:56:47.992 UTC [2424317] misskey@misskey STATEMENT:  INSERT INTO "user_profile"("userId", "location", "birthday", "description", "fields", "lang", "url", "email", "emailVerifyCode", "emailVerified", "emailNotificationTypes",
"twoFactorTempSecret", "twoFactorSecret", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "password", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "pinnedPageId", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes", "userHost") VALUES ($1, $2, $3, $4, $5, DEFAULT, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7) RETURNING "fields", "emailVerified", "emailNotificationTypes", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes"
2021-05-31 17:56:50.905 UTC [2424316] misskey@misskey ERROR:  value too long for type character varying(1024)
2021-05-31 17:56:50.905 UTC [2424316] misskey@misskey STATEMENT:  INSERT INTO "user_profile"("userId", "location", "birthday", "description", "fields", "lang", "url", "email", "emailVerifyCode", "emailVerified", "emailNotificationTypes",
"twoFactorTempSecret", "twoFactorSecret", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "password", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "pinnedPageId", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes", "userHost") VALUES ($1, $2, $3, $4, $5, DEFAULT, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7) RETURNING "fields", "emailVerified", "emailNotificationTypes", "twoFactorEnabled", "securityKeysAvailable", "usePasswordLessLogin", "clientData", "room", "autoAcceptFollowed", "noCrawle", "alwaysMarkNsfw", "carefulBot", "injectFeaturedNote", "receiveAnnouncementEmail", "integrations", "enableWordMute", "mutedWords", "mutingNotificationTypes"
2021-05-31 18:03:58.607 UTC [2431464] misskey@misskey ERROR:  value too long for type character varying(512)
2021-05-31 18:03:58.607 UTC [2431464] misskey@misskey STATEMENT:  INSERT INTO "drive_file"("id", "createdAt", "userId", "userHost", "md5", "name", "type", "size", "comment", "blurhash", "properties", "storedInternal", "url", "thumbnailUrl", "webpublicUrl", "accessKey", "thumbnailAccessKey", "webpublicAccessKey", "uri", "src", "folderId", "isSensitive", "isLink") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, DEFAULT, DEFAULT, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "properties", "isSensitive", "isLink"
2021-05-31 18:11:05.309 UTC [2438645] misskey@misskey ERROR:  value too long for type character varying(512)
2021-05-31 18:11:05.309 UTC [2438645] misskey@misskey STATEMENT:  INSERT INTO "drive_file"("id", "createdAt", "userId", "userHost", "md5", "name", "type", "size", "comment", "blurhash", "properties", "storedInternal", "url", "thumbnailUrl", "webpublicUrl", "accessKey", "thumbnailAccessKey", "webpublicAccessKey", "uri", "src", "folderId", "isSensitive", "isLink") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, DEFAULT, DEFAULT, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "properties", "isSensitive", "isLink"
```

**Comment by Kusoneko** [comment]
From that alone it seems to me that the issue would be that whatever is limited to type character varying(512) and (1024) should be increased and the problem would just vanish afterwards as it seems to be caused by attemps to insert content that is of a greater length than the limit allows. I'm not sure where the DB migrations are setup in the codebase, but making a PR that would make a migration leading to a larger size on these fields would presumably fix it, assuming the issue is strictly there and what the misskey logs return is essentially what postgresql returns as an error, rather than a hard-coded error in misskey.

**Comment by okpierre** [comment]
It is something @syuilo and the dev team will have to look into.

I really hope there will be more focus on fixes instead of new features.

**Comment by Kusoneko** [comment]
If nothing is done about it by the time I get enough free time, I might look into trying to fix it and then open a PR with the fix. Though, that's only if I manage to find some free time and get a good enough understanding of the code to figure out how to make the changes required to fix this.
