### ISSUE TITLE
typeorm 0.2.33 以降ではテストでDBに接続できない

### ISSUE THREAD

**Issue by mei23** [misskey-dev/misskey#7565]
## 💡 Summary
typeorm 0.2.33 以降ではテストでDBに接続できない

quietを無効にするとこのあたりが出てる
```
ERR  *	[core boot db]	Cannot connect
ERR  *	[core boot db]	TypeError: Cannot read property 'substring' of undefined
```

```
     TypeError: Cannot read property 'substring' of undefined
      at PostgresDriver.defaultEqual (src/driver/postgres/PostgresDriver.ts:774:59)
      at /home/runner/work/misskey/misskey/src/driver/postgres/PostgresDriver.ts:904:55
      at Array.filter (<anonymous>)
      at PostgresDriver.findChangedColumns (src/driver/postgres/PostgresDriver.ts:892:32)
      at /home/runner/work/misskey/misskey/src/schema-builder/RdbmsSchemaBuilder.ts:519:59
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:128:143)
      at Object.next (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at /home/runner/work/misskey/misskey/node_modules/typeorm/node_modules/tslib/tslib.js:117:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/typeorm/node_modules/tslib/tslib.js:113:16)
      at RdbmsSchemaBuilder.updateExistColumns (node_modules/typeorm/schema-builder/RdbmsSchemaBuilder.js:1095:24)
      at RdbmsSchemaBuilder.<anonymous> (src/schema-builder/RdbmsSchemaBuilder.ts:168:20)
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
      at Object.next (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at fulfilled (node_modules/typeorm/node_modules/tslib/tslib.js:114:62)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

https://github.com/misskey-dev/misskey/issues/7547#issuecomment-858227361

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by mei23** [comment]
synchronizeあたりで失敗するぽい

**Comment by mei23** [comment]
typeorm v0.2.35 以降では修正されている
https://github.com/typeorm/typeorm/pull/7816
