### ISSUE TITLE
Error: invalid Actor: summary invalid-range

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#7627]
Sorry, I can't read Japanese, so I don't know if this error has already been reported.

## 💡 Summary

Sometimes I will get the error "Error: invalid Actor: summary invalid-range" in logs when a new remote post is received.

## 🙂 Expected Behavior

No error occurs.

## ☹️ Actual Behavior

```js
04:17:17 INFO *	[remote ap]	Creating the Note: https://poa.st/objects/44cc7ccb-f458-428f-b6c6-80638c468c1b
04:17:17 WARN *	[remote ap]	Error in announce target https://poa.st/objects/44cc7ccb-f458-428f-b6c6-80638c468c1b - Error: invalid Actor: summary invalid-range
Error: invalid Actor: summary invalid-range
    at validate (/misskey/built/remote/activitypub/models/person.js:48:19)
    at validateActor (/misskey/built/remote/activitypub/models/person.js:54:5)
    at createPerson (/misskey/built/remote/activitypub/models/person.js:102:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.resolvePerson (/misskey/built/remote/activitypub/models/person.js:333:12)
    at async createNote (/misskey/built/remote/activitypub/models/note.js:78:19)
    at async Object.resolveNote (/misskey/built/remote/activitypub/models/note.js:252:16)
    at async Object.default_1 [as default] (/misskey/built/remote/activitypub/kernel/announce/note.js:35:22)
```

## 📝 Steps to Reproduce

I don't know how to reproduce this, maybe it is possible to reproduce if you try to fetch the note with the url above.

## 📌 Environment

Misskey 12.85.1 in Docker

**Comment by mei23** [comment]
Fixed with #7629
